server:
  port: 4006
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

api:
  prefix: /api/v1

spring:
  application:
    name: auth-service

  output:
    ansi:
      enabled: ALWAYS

  datasource:
    url: jdbc:h2:file:./stores/h2/auth_data/mydb;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  messages:
    basename: i18n/messages
    encoding: UTF-8

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 12313
            clientSecret: 12332

  h2:
    console:
      enabled: true
      path: /api/v1/h2-console

  cloud:
    discovery:
      enabled: true
      eureka:
        client:
          serviceUrl:
            defaultZone: http://localhost:8761/eureka/  # Eureka Server URL

  data:
    redis:
      host: localhost
      port: 6379

jwt:
  expiration: 2592000 #30 days = 30 * 24 * 60 * 60
  expiration-refresh-token: 5184000 #60 days = 60 * 24 * 60 * 60
  secretKey: 7AFc4eOXfC4u76ZtsXaWOqbx83z0O

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha

  api-docs:
    enabled: true

logging:
  level:
    root: DEBUG
    org.springframework: DEBUG
    springframework.security: DEBUG
    org.hibernate: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    javax.management: off
    sun.rmi: off
    sun.rmi.transport.tcp: off
    sun.rmi.loader: off

#health check
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "health,info,prometheus"
  endpoint:
    health:
      show-details: always
    metrics:
      access: unrestricted
    prometheus:
      access: unrestricted