networks:
  shopee_network:
    driver: bridge

services:
  eureka:
    container_name: eureka-server
    build:
      context: .
      dockerfile: eureka-service/Dockerfile
    ports:
      - "8761:8761"
    restart: on-failure
    volumes:
      - ./logs/eureka:/logs/eureka
    networks:
      - shopee_network

  gateway:
    container_name: gateway-service
    build:
      context: .
      dockerfile: gateway-service/Dockerfile
    ports:
      - "4003:4003"
    restart: on-failure
    volumes:
    - ./logs/gateway:/logs/gateway
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - eureka
    networks:
      - shopee_network

  notification-service:
    container_name: notification-service
    build:
      context: .
      dockerfile: notification-service/Dockerfile
    ports:
      - "4005:4005"
    depends_on:
      - eureka
      - gateway
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    volumes:
      - ./stores/h2/notification_data:/data
      - ./logs/notification:/logs/notification
    networks:
      - shopee_network

  auth-service:
    container_name: auth-service
    build:
      context: .
      dockerfile: auth-service/Dockerfile
    ports:
      - "4006:4006"
    depends_on:
      - eureka
      - gateway
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    volumes:
      - ./logs/auth:/logs/auth
      - ./stores/h2/auth_data:/data
    networks:
      - shopee_network