### Post request
POST {{auth-service.host}}/api/v1/auth/register
Content-Type: application/json

{
  "name": "Hoang Cao Luu",
  "email": "hoangclw@gmail.com",
  "phoneNumber": "0854123561",
  "gender": "MALE",
  "password": "1"
}

### Post request
POST {{auth-service.host}}/api/v1/auth/login
Content-Type: application/json

{
  "email": "hoangclw@gmail.com",
  "password": "string"
}


### Post request
POST {{auth-service.host}}/api/v1/auth/generate-token-from-email
Content-Type: application/json

{
  "email": "hoangclw@gmail.com"
}