server:
  port: 4003

spring:
  main:
    web-application-type: reactive

  application:
    name: gateway-service
  cloud:
    discovery:
      enabled: true
      eureka:
        client:
          serviceUrl:
            defaultZone: http://localhost:8761/eureka/  # Eureka Server URL
    gateway:
      routes:
        - id: kt-service-route
          uri: lb://kt-service  # Use the service name registered in Eureka
          predicates:
            - Path=/kt-service/**

        - id: auth-service-route
          uri: lb://auth-service  # Use the service name registered in Eureka
          predicates:
            - Path=/auth-service/**

        - id: jv-service-route
          uri: lb://jv-service  # Use the service name registered in Eureka
          predicates:
            - Path=/jv-service/**


  output:
    ansi:
      enabled: ALWAYS

jwt:
  expiration: ${JWT_EXPIRATION:2592000}
  expiration-refresh-token: ${JWT_EXPIRATION_REFRESH_TOKEN:5184000}
  secretKey: ${JWT_SECRET_KEY:TaqlmGv1iEDMRiFp/pHuID1+T84IABfuA0xXh4GhiUI=}

logging:
  level:
    root: info
    org.springframework: DEBUG
    springframework.security: DEBUG
    org.hibernate: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

#health check
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "health,info,prometheus"
  endpoint:
    health:
      show-details: always
    metrics:
      access: unrestricted
    prometheus:
      access: unrestricted