networks:
  shoppe_network:
    driver: bridge

services:
  shoppe:
    image: lcaohoanq/shoppe
    container_name: shoppe_spcserver
    build:
      context: ..
      dockerfile: docker/Dockerfile
    restart: on-failure
    ports:
      - "8080:8080"
    networks:
      - shoppe_network
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      redis-container:
        condition: service_healthy

  redis-container:
    image: docker.io/redis:7.2.3
    container_name: redis_shoppee
    restart: no
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data # Mount a volume for Redis data persistence
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli", "ping" ]
    networks:
      - shoppe_network

volumes:
  redis_data:
    driver: local
