server:
  port: 4004
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

api:
  prefix: /api/v1

spring:
  application:
    name: product-service

  output:
    ansi:
      enabled: ALWAYS

  datasource:
    url: jdbc:h2:file:./stores/h2/product_data/mydb;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  messages:
    basename: i18n/messages
    encoding: UTF-8

  cloud:
    discovery:
      enabled: true
      eureka:
        client:
          serviceUrl:
            defaultZone: http://localhost:8761/eureka/  # Eureka Server URL

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha

  api-docs:
    enabled: true

logging:
  level:
    root: info
    org.springframework: DEBUG
    springframework.security: DEBUG
    org.hibernate: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

#health check
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "health,info,prometheus"
  endpoint:
    health:
      show-details: always
    metrics:
      access: unrestricted
    prometheus:
      access: unrestricted