spring:
  application:
    name: eureka-server
  cloud:
    discovery:
      eureka:
        client:
          registerWithEureka: false
          fetchRegistry: false
server:
  port: 8761  # Eureka server will run on this port by default

#health check
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "health,info,prometheus"
  endpoint:
    health:
      show-details: always
    metrics:
      access: unrestricted
    prometheus:
      access: unrestricted