name: Continuous Deployment
on:
  push:
    branches:
      - develop
    paths-ignore:
      - '**.md'
      - 'docs/**'

env:
  REGISTRY: docker.io
  IMAGE_NAME: lcaohoanq/shoppe

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create .env file
        run: |
          cat << EOF > .env
          POSTGRES_USER=${{ secrets.MYSQL_DATASOURCE }}
          POSTGRES_PASSWORD=${{ secrets.MYSQL_USER }}
          MAIL_USERNAME=${{ secrets.MYSQL_PASSWORD }}
          MAIL_PASSWORD=${{ secrets.MYSQL_DEV_USER }}
          DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }}
          JWT_EXPIRATION=${{ secrets.JWT_EXPIRATION }}
          JWT_EXPIRATION_REFRESH_TOKEN=${{ secrets.JWT_EXPIRATION_REFRESH_TOKEN }}
          JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}
          EOF

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./SPCServer/springboot/docker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/shoppe:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Stop and remove old container
        run: docker container stop shoppe || true
        
      - name: Deploy with Docker Compose
        working-directory: SPCServer/springboot
        run: |
          docker compose -f docker/docker-compose-prod.yml up -d --build --remove-orphans
