name: Continuous Deployment

on:
  push:
    branches:
      - develop
    paths-ignore:
      - '**.md'
      - 'docs/**'

jobs:
  # Job 1: Checkout and create .env file
  create-env:
    runs-on: ubuntu-24.04
    outputs:
      env-file: ${{ steps.create-env.outputs.env-file }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create .env file
        id: create-env
        working-directory: docker
        run: |
          echo "SPRING_PROFILES_ACTIVE=${{ secrets.SPRING_PROFILES_ACTIVE }}" >> .env
          echo "SPRING_DATASOURCE_URL=${{ secrets.SPRING_DATASOURCE_URL }}" >> .env
          echo "SPRING_DATASOURCE_USERNAME=${{ secrets.SPRING_DATASOURCE_USERNAME }}" >> .env
          echo "SPRING_DATASOURCE_PASSWORD=${{ secrets.SPRING_DATASOURCE_PASSWORD }}" >> .env
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env

      - name: Create .env file
        id: create-env-spcserver-springboot
        working-directory: spcserver/springboot
        run: |
          echo "SPRING_PROFILES_ACTIVE=${{ secrets.SPRING_PROFILES_ACTIVE }}" >> .env
          echo "SPRING_DATASOURCE_URL=${{ secrets.SPRING_DATASOURCE_URL }}" >> .env
          echo "SPRING_DATASOURCE_USERNAME=${{ secrets.SPRING_DATASOURCE_USERNAME }}" >> .env
          echo "SPRING_DATASOURCE_PASSWORD=${{ secrets.SPRING_DATASOURCE_PASSWORD }}" >> .env
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
          echo "MAIL_USERNAME=${{ secrets.MAIL_USERNAME }}" >> .env
          echo "MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}" >> .env
          echo "JWT_EXPIRATION=${{ secrets.JWT_EXPIRATION }}" >> .env
          echo "JWT_EXPIRATION_REFRESH_TOKEN=${{ secrets.JWT_EXPIRATION_REFRESH_TOKEN }}" >> .env
          echo "JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}" >> .env
            
      - name: Verify .env file creation
        run: ls -al docker && ls -al spcserver/springboot

  cache-maven:
    runs-on: ubuntu-24.04
    needs: create-env
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-
            maven-

  run-docker-compose:
    runs-on: ubuntu-24.04
    needs: cache-maven
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker stop old container
        run: docker container stop shoppe || true

      - name: Docker Compose Up
        run: docker compose -f docker/docker-compose-prod.yml up -d --build --remove-orphans
  
  # Job 3: Build Docker image
  build-docker:
    runs-on: ubuntu-24.04
    needs: [ create-env , cache-maven ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -f docker/Dockerfile-SpringBoot -t ${{ secrets.DOCKER_USERNAME }}/shoppe:latest .

  # Job 4: Push image to Docker Hub
  push-docker-image:
    runs-on: ubuntu-24.04
    needs: build-docker
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          node-version: '20'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push built image to DockerHub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/shoppe:latest

      - name: Log out from DockerHub
        run: docker logout
