name: CI for Koi-Auction-BE

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run All Unit Tests
        working-directory: ./SPCServer/springboot
        run: mvn -B clean test --file pom.xml
        env:
          SPRING_PROFILES_ACTIVE: test


