name: SPC-CI-Unit-Test

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "develop" ]
    
jobs:
  run-tests:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        project:
         - spcserver/springboot
         
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
          
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run Unit Tests for ${{ matrix.project }}
        run: mvn -B clean test --file ${{ matrix.project }}/pom.xml
        env:
          SPRING_PROFILES_ACTIVE: ${{ contains(matrix.project, 'springboot') && 'test' || '' }}


