name: CI for Koi-Auction-BE

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "develop" ]
    
jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
          
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run All Unit Tests
        working-directory: ./SPCServer/springboot
        run: mvn -B clean test --file pom.xml
        env:
          SPRING_PROFILES_ACTIVE: test


